services:
  caass-auth:
    build:
      context: .
      dockerfile: CAASS.Auth/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Use appsettings.Development.Docker.json instead of appsettings.Development.json
      # in the container
      - ASPNETCORE_ENVIRONMENT=Development.Docker
      - ASPNETCORE_URLS=http://*:8080 # Set listen address
    ports:
      - "9090:8080"
    networks:
      - caass-network

  db:
    image: postgres:16
    restart: unless-stopped
    container_name: caass_tenants
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bluesky1!
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - caass-network

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8080"
    networks:
      - caass-network

# Add future solutions here as new services

networks:
  caass-network:
    driver: bridge
    
volumes:
  postgres_data: